### ISSUE TITLE
September 2018 test-fix ready for review/QC

### ISSUE THREAD

**Issue by kylebunting** [Microsoft/MCW-Data-Platform-upgrade-and-migration#12]
The sept-2018-test-fix branch is ready for review/QC.

**Comment by DawnmarieDesJardins** [comment]
Hey Kyle,
Can you please check line 1449 on the HOL?  The code is:
'''sql
USE master;
GO.....

I'm not sure if there is supposed to be a hard return after the ''' so that the sql line shows in the document?

**Comment by kylebunting** [comment]
Dawnmarie, the document is correct as is. The "sql" on the same line as the three ticks indicates the language contained within the code block. That allows markdown to apply formatting/coloring of the text, based on the language being specified. If, for example, the code within the block was C#, you would see ```csharp. In this case, it is SQL, hence the ```sql line.

**Comment by DawnmarieDesJardins** [comment]
Got it!  It looked a little different than the others so I figured I'd ask. I appreciate the explanation, now I know.  Branches merged & HTML updated. I ran Keros and PoliCheck. Please send over the compliance doc for my files.  Closing issue
