### ISSUE TITLE
HOL step by step lab : Solution architecture

### ISSUE THREAD

**Issue by Abhishekpathania01** [Microsoft/MCW-Data-Platform-upgrade-and-migration#15]
Can someone check on Solution Architecture which has provided in the HOL- step by step.
May i know why Azure SQL Datawarehouse is there in preferred architecture when there is no mention about it in the overall solution? Can we update that in documentation?

![image](https://user-images.githubusercontent.com/38715522/48671677-fe87ef80-eb51-11e8-83d9-4f798b6aefd2.png)

**Comment by DawnmarieDesJardins** [comment]
Assigning to Kyle for review.

**Comment by kylebunting** [comment]
The preferred solution diagram has been updated to change the use of Azure SQL Data Warehouse to Azure SQL Stretch Database, used to extend the audit log table into Azure.

![image](https://user-images.githubusercontent.com/5960229/48780563-3acd6400-eca8-11e8-808b-6260e754aa04.png)
