### ISSUE TITLE
csc.exe file is missing from MCW-Data-Platform-upgrade-and-migration-master\Hands-on lab\lab-files\starter-project\NorthwindMVC\bin\roslyn\csc.exe

### ISSUE THREAD

**Issue by akn9050** [Microsoft/MCW-Data-Platform-upgrade-and-migration#19]
When running starter project in [Exercise 4 -Task 6](https://github.com/Microsoft/MCW-Data-Platform-upgrade-and-migration/blob/master/Hands-on%20lab/HOL%20step-by-step%20-%20Data%20Platform%20upgrade%20and%20migration.md#task-6-configure-the-starter-application-to-use-oracle), Showing below error.
Server Error in '/' Application.

Could not find a part of the path 'C:\handsonlab\MCW-Data-Platform-upgrade-and-migration-master\Hands-on lab\lab-files\starter-project\NorthwindMVC\bin\roslyn\csc.exe'. 
  Description: An unhandled exception occurred during the execution of the current web request. Please review the stack trace for more information about the error and where it originated in the code. 

 Exception Details: System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\handsonlab\MCW-Data-Platform-upgrade-and-migration-master\Hands-on lab\lab-files\starter-project\NorthwindMVC\bin\roslyn\csc.exe'.

![snag_10f198c](https://user-images.githubusercontent.com/27498287/52129320-3dabe400-265d-11e9-93c2-c3f603859f93.png)

**Comment by kylebunting** [comment]
@akn9050, can you verify that you see the following in the .csproj file for the NorthwindMVC project?

```xml
<Target Name="CopyRoslynFiles" AfterTargets="AfterBuild" Condition="!$(Disable_CopyWebApplication) And '$(OutDir)' != '$(OutputPath)'">
    <ItemGroup>
      <RoslynFiles Include="$(CscToolPath)\*" />
    </ItemGroup>
    <MakeDir Directories="$(WebProjectOutputDir)\bin\roslyn" />
    <Copy SourceFiles="@(RoslynFiles)" DestinationFolder="$(WebProjectOutputDir)\bin\roslyn" SkipUnchangedFiles="true" Retries="$(CopyRetryCount)" RetryDelayMilliseconds="$(CopyRetryDelayMilliseconds)" />
</Target>
```

It should be around line 1001 in the .csproj file.

**Comment by akn9050** [comment]
Hi @kylebunting I am not able to this file for NorthwindMVC project

![image](https://user-images.githubusercontent.com/27498287/52131529-f9234700-2662-11e9-8aca-38ddf2d624a9.png)

**Comment by kylebunting** [comment]
@akn9050 you will need to look in the project directory in the file system, not in Visual Studio. If that block is in the file, you may also need to reinstall the Nuget packages for the project. You can do that by running the following command from the Package Manager Console in Visual Studio:

```powershell
Update-Package -reinstall
```

**Comment by akn9050** [comment]
Thanks, this worked.

**Comment by akn9050** [comment]
@kylebunting One more thing. When executing sql assembly query in exercise 5 step 43.
In below query when pasting binary data and executing the query its showing "Msg 103, Level 15, State 4, Line 5
The identifier that starts with '0x4D5A90000300000004000000FFFF0000B800000000000000400000000000000000000000000000000000000000000000000000000000000000000000800000' is too long. Maximum length is 128.
"

USE master;
GO

DECLARE @clrName nvarchar(4000) = 'SSMA4OracleSQLServerCollections.NET'
DECLARE @asmBin varbinary(max) = [INSERT BINARY];
DECLARE @hash varbinary(64);

SELECT @hash = HASHBYTES('SHA2_512', @asmBin);

EXEC sys.sp_add_trusted_assembly @hash = @hash, @description = @clrName;

**Comment by akn9050** [comment]
Below one is working please update this in lab guide. Need to replace INSERT BINARY with actual binary from already saved assembly script.

USE master;
GO

DECLARE @clrName nvarchar(4000) = 'SSMA4OracleSQLServerCollections.NET'
DECLARE @asmBin varbinary(max);
set @asmBin = **INSERT BINARY**

DECLARE @hash varbinary(64);

SELECT @hash = HASHBYTES('SHA2_512', @asmBin);

EXEC sys.sp_add_trusted_assembly @hash = @hash, @description = @clrName;

**Comment by kylebunting** [comment]
@akn9050, interesting on the last point. I've not run into that, but see no issue in updating the SQL code to perform the variable assignment as you have done above. I'll make a note about this, so that during the next update for this lab that is reviewed.
