### ISSUE TITLE
No Peering between DMS and SQL2008R2 VM

### ISSUE THREAD

**Issue by pankaj1102** [Microsoft/MCW-Data-Platform-upgrade-and-migration#20]
Hi - SQL2008R2 VM is on a different VNET to Azure DMS but there's no step to peer the two. Would recommend changing instructions to deploy the DMS to the same vnet/subnet as the SQL 2008R2 VM.

**Comment by DawnmarieDesJardins** [comment]
Thanks pankaj1102!
Labelling this issue as an enhancement to be address in the next update.

**Comment by kylebunting** [comment]
@pankaj1102, this has been fixed in the latest pull request for the April 2019 test-fix of the workshop. Closing this issue.
