### ISSUE TITLE
Bug - SQL 2008 or 2008 R2?

### ISSUE THREAD

**Issue by mwasham** [microsoft/MCW-Data-Platform-upgrade-and-migration#23]
The before the HOL states to deploy 2008 R2 and SQL 2017. Exercise 1 screenshots/steps have steps to connect to SQL 2008 (no R2).

**Comment by DawnmarieDesJardins** [comment]
@kylebunting 
Hi Kyle, 
Please review and advise.  (Let me know if I should assign to someone else.)
Thanks, Dawnamrie

**Comment by kylebunting** [comment]
This appears to just be a screenshot issue. SQL 2008 R2 is used throughout. A few screen shots are reflecting a VM name of SqlServer2008 and not SqlServer2008R2 I'll update the screen shots so it is consistent.

**Comment by kylebunting** [comment]
Fixed this issue. Updated language and screenshots for consistency in referring to the VM name. Added in commit 9a7f47e.
