### ISSUE TITLE
Ex 5: Migrate the Oracle database to SQL Server 2017

### ISSUE THREAD

**Issue by ac2707** [microsoft/MCW-Data-Platform-upgrade-and-migration#24]
In the Oracle Metadata Explorer, check the box next to NW, expand the NW database, and un-check Packages. Next, click on NW to make sure it is selected in the tree.

If I convert the schema by un-checking the Packages, get errors for all the procedures because the cursor type is defined in the package. Please advise.

Also, If i include the package I get the below errors - 
![image](https://user-images.githubusercontent.com/49182510/62271942-864f2900-b457-11e9-8cf0-da0498d99291.png)

![image](https://user-images.githubusercontent.com/49182510/62279139-1ea0da00-b467-11e9-961c-fa29ab904297.png)

Please advise. Thanks.

**Comment by ac2707** [comment]
Could proceed on this one - just had to exclude the invalid stored procedure - GetCustomersTest.

Thanks.

**Comment by DawnmarieDesJardins** [comment]
Closing as resolved.  Thanks!
