### ISSUE TITLE
Issue in Exercise3 - Data Compression not supported.

### ISSUE THREAD

**Issue by tejaswini972** [microsoft/MCW-Data-Platform-upgrade-and-migration#29]
In **Exercise 3 Task 1 step 7**,  SQL Server 2008 R2 doesn't support **data compression.** 
Enclosing image for reference.

![image001](https://user-images.githubusercontent.com/52440474/85832129-20753980-b7ad-11ea-9bf0-cce705c282d0.jpg)

**Comment by kylebunting** [comment]
@tejaswini972, it looks like perhaps you missed a step. Exercise 3, Task 1, Step 1 has you connect to the Azure SQL Database you migrated to in the previous exercise. That is the database you will perform compression against, not the SQL Server 2008 R2 instance of the database.

**Comment by DawnmarieDesJardins** [comment]
@tejaswini972 
Hello!  Has this been resolved?  May we close the issue?
Thank you.

**Comment by tejaswini972** [comment]
@DawnmarieDesJardins 
Hi,
The issue is resolved. You can close the issue.
Thank you.

**Comment by DawnmarieDesJardins** [comment]
Spectacular...thanks so much!  Closing as resolved.
