### ISSUE TITLE
SQL Server 2017 Image

### ISSUE THREAD

**Issue by ctgunawan** [Microsoft/MCW-Data-Platform-upgrade-and-migration#3]
Can you use SQL Server 2017 image instead to combine Exercise 1 - Task 1, Task 2 and Task 3? It will help minimize the effort to install the OS and SQL Server respectively

**Comment by kylebunting** [comment]
@ctgunawan, I like this idea, and I think it is something we can do, but it will require several changes to the lab that will take more time than is available for this update. This will mean there are three VMs for the lab, LabVM, SqlServer2008, and SqlServer2017. As SQL 2008 is currently a named instance, steps around accessing that will need to be updated as well.

I'll leave this issue open so it can be considered for the next update.

**Comment by DawnmarieDesJardins** [comment]
December 2018 closes this issue.
