### ISSUE TITLE
Before the HOL

### ISSUE THREAD

**Issue by DawnmarieDesJardins** [Microsoft/MCW-Data-Platform-upgrade-and-migration#7]
I corrected file name to Before the HOL (from Before the lab) - please check that didn't break any links. (I found and updated 2 in the step-by-step lab)

I added updated headers and licensing at the top.  The template has a Requirements section.  I added it to the document, please fill in that section.

I removed your Next Steps section since it's not on the current template.  We could put that in as a future enhancement/add to workshops if you'd like?

**Comment by kylebunting** [comment]
Fixed.
